 /*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.stefanbratanov.jvm.openai.*;

import java.util.ArrayList;
import java.util.List;

public class App {
    public static int RequestCount = 0;

    public static String MakeSomeComplexAdditionToTheMessage(String userMessage) {
        userMessage = userMessage + ". Please be concise. Short answer only.";
        return userMessage;
    }





    
    public static String AskOpenAIConcisely(List<String> previousMessages, String userMessage) {
        userMessage = MakeSomeComplexAdditionToTheMessage(userMessage);

        System.out.println();
        System.out.println("-------------------------");
        System.out.println("REQUEST #: " + RequestCount);
        System.out.println();
        System.out.println("PREVIOUS MESSAGES: ");
        for (var pm : previousMessages) {
            System.out.println(pm);
        }

        System.out.println();
        System.out.println("USER: " + userMessage);
        String response = CallOpenAIHelper(previousMessages, userMessage);

        System.out.println();
        System.out.println("SYSTEM: " + response);


        RequestCount++;

        return response;
    }

    public static String CallOpenAIHelper(List<String> previousMessages, String userMessage) {
        previousMessages.add(userMessage);
        var answer = OpenAI.CallOpenAI(previousMessages, userMessage);
        previousMessages.add(answer);
        return answer;
    }

    // Placeholder function for OpenAI
    public static String CallOpenAIStub(List<String> previousMessages, String userMessage) {
        previousMessages.add(userMessage);
        var answer =  "This is a fake response that's shorter from OpenAI";
        previousMessages.add(answer);
        return answer;
    }

    public static void main(String[] args) {
        List<String> previousMessages = new ArrayList<>();

        String response0 = AskOpenAIConcisely(previousMessages, "Tell me how to be a better programmer.");
        //System.out.println(response0);

        String response1 = AskOpenAIConcisely(previousMessages,"Tell me how to be a better manager.");
        // System.out.println(response1);

    }
}
